### ISSUE TITLE
Different results on different computers

### ISSUE THREAD

**Issue by padsley** [padsley/AngCorPackage#2]
The problem with negative numbers only seems to appear on an Ubuntu machine. We've seen it on two machines and it's possibly caused by the compiler or the architecture.

Trying to work this out now.

**Comment by padsley** [comment]
Below are pictures of the outputs of AngCor for the same input file on a Mac (green text) and an Ubuntu machine (white text). These answers are obviously and problematically different.

Changing gfortran version and compile flags for the standard (-std=legacy,f95) etc. didn't help. Notably some of the warnings which come from running make without specifying the standard are suppressed when running with older standards specified in the flag but the results produced by AngCor don't seem to be different in each case.

![WhatsApp Image 2019-08-27 at 16 43 09 (1)](https://user-images.githubusercontent.com/8112824/64014947-b9064300-cb23-11e9-9f21-c1e6bec8546e.jpeg)
![WhatsApp Image 2019-08-27 at 16 43 09](https://user-images.githubusercontent.com/8112824/64014964-c3c0d800-cb23-11e9-8717-f0f0ea480276.jpeg)

**Comment by padsley** [comment]
Next steps would be:

1. Check that fort.2 files are identical - make sure that the problem isn't CHUCK.
2. Increase the verbosity of AngCor - see if we can get it to print out more steps as it goes along - this may require ICO value changes or adding "write" statements to the FORTRAN codes to get them to be a bit more communicative.
3. If we're seeing this discrepant behaviour, we may need to contact the people who maintain gfortran to let them know that there are problems - though they may say that this is a known issue and something that should be fixed by us not doing something particular in the code itself.
4. Compiling on Ubuntu - iirc, Ubuntu dropped static linking (?) and so (at least with C/C++) when compiling you have to link yourself (hence all of the root-config --cflags --libs bits in Makefiles). Does something similar need to happen on Ubuntu as well? Could it be that some of the libraries are not linking properly due to the system architecture? (I'm just making stuff up now - I've got no idea.)
5. Implicit none etc in subroutines - maybe Ubuntu doesn't deal well with e.g. implicit declarations in subroutines, I know that this can cause problems if one isn't careful from past experience. This may be something to test - do the subroutines used to calculate some variables/functions fail due to Ubuntu being more fussy about declarations/linking etc than other OSs?

That's all that I can think of for now.

For testing purposes, I'm tagging in @pellegri because she's got both access to both OSs and it may be easier for her to test things than for me to test them.

**Comment by padsley** [comment]
Luke sent me the Koln version of the code and it looks like the only difference is in c.f:

`COMPLEX FUNCTION C*16(L,M,PHI)`	vs `COMPLEX*16 FUNCTION C(L,M,PHI)	`

**Comment by padsley** [comment]
I've been thinking about this and:

c.f is a short piece of code. I think that I can probably try to debug it fairly easily looking at the print statements that result from it. Failing that, maybe an alternative formulation of the code may allow the errors to be avoided - the problem is that I also need to be able to test on a Mac to see whether this code works there.

It may be that this subroutine needs to be implemented differently for Macs and true Linux systems?

**Comment by padsley** [comment]
From what I can tell, the function "C" is invoked at:

```
sigma.f:20:	  SIG1 = SIG1 + RHO(KMQ)*C(KK,MQ,PHI)
sigma.f:22:	  SIG1 = SIG1 +RHO(KMQ)*C(KK,MQ,PHI)*RKK(KK/2)*ZW(KK/2)
```

**Comment by pellegri** [comment]
I’ll be back on Tuesday and we can check on my laptop how it is ;)

L


**********************************************************************************************
Dr Luna Pellegri
University of the Witwatersrand and iThemba LABS
iThemba LABS, P.O. Box 722, Somerset West, 7129, South Africa 
+27 (0)21 8431136 (Work Phone)
+27 (0)71 3204629 (SA Mobile)
**********************************************************************************************

**Comment by padsley** [comment]
Angular correlations are weighted with the cross sections already - see line 915 in angcorm.f.

**Comment by padsley** [comment]
Having chased down the problem a little bit more - I think that the place to spend a bit of time looking is the value `SIG(I)` in `gamcor.f`. This value is set by calling the subroutine `SIGMA` found in `sigma.f` which, in turn, involves `RHO` and `C` which are in `rhokq.f` and `c.f`. I think that `rhokq.f` is likely where the problem is originating (given what Luke said about his discussions with Muhsin). But we should also check `C` because we know that that's different between the Koln version and the... uh... other version?

**Comment by padsley** [comment]
[output_Sept14.txt](https://github.com/padsley/AngCorPackage/files/3612630/output_Sept14.txt)

Currently have this output - this is by adding `WRITE` statements into `sigma.f`.

This should allow us to test which part of the code - the rhos or the Cs - are causing the problem.

Before sigma.f had:

```
	IF (KK.EQ.0) THEN
	  SIG1 = SIG1 + RHO(KMQ)*C(KK,MQ,PHI)
	ELSE
	  SIG1 = SIG1 + RHO(KMQ)*C(KK,MQ,PHI)*RKK(KK/2)*ZW(KK/2)
	ENDIF
```
and now:
```
	IF (KK.EQ.0) THEN
	  SIG1 = SIG1 + RHO(KMQ)*C(KK,MQ,PHI)
	  WRITE(*,*)"KK==0"
	  WRITE(*,*)"RHO(KMQ) = ",RHO(KMQ)
	  WRITE(*,*)"C(KK,MQ,PHI) = ",C(KK,MQ,PHI)
	ELSE
	  SIG1 = SIG1 + RHO(KMQ)*C(KK,MQ,PHI)*RKK(KK/2)*ZW(KK/2)
	  WRITE(*,*)"KK!=0"
	  WRITE(*,*)"RHO(KMQ) = ",RHO(KMQ)
	  WRITE(*,*)"C(KK,MQ,PHI) = ",C(KK,MQ,PHI)
	  WRITE(*,*)"RKK(KK/2) = ",RKK(KK/2)
	  WRITE(*,*)"ZW(KK/2) = ",ZW(KK/2)
	ENDIF
```

**Comment by padsley** [comment]
I also have left in a `WRITE` statement from somewhere else in the output file - I need to find this first because this will result in different output files when we do the comparison.

**Comment by padsley** [comment]
I've just tried with g77 with -m32 as the compilation option but that doesn't seem to work either. I get NANs for the outputs instead of negatives though. Which is different I guess?

**Comment by padsley** [comment]
However, I have managed to get the Koln executable working on an Ubuntu system - using the destructions here: https://nukephysik101.wordpress.com/2017/04/05/compiling-fortran77-code-in-ubuntu-16/

I don't know who that is, by the way, but it seems to be One Of Us.

**Comment by padsley** [comment]
We have recompiled on a Mac system and that system does **not** work properly - i.e. we see exactly the same output on the Mac as on an Ubuntu system so whatever issues are occurring are (maybe) not system-dependent.

**Comment by padsley** [comment]
Other things to check - other compiler flags?

**Comment by padsley** [comment]
Output of ldd on the pre-build binary and my local version:

`ldd angcor` gives

```
	linux-vdso.so.1 =>  (0x00007fb0a90ef000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fb0a8ba1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb0a8898000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb0a8682000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb0a82b8000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fb0a8079000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb0a8ecc000)
```
and the Koln version gives

```
	linux-vdso.so.1 =>  (0x00007fff2e2fe000)
	libg2c.so.0 => /usr/lib/libg2c.so.0 (0x00007f873c4f6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f873c1ed000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f873bfd7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f873bc0d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f873c726000)
```

The differences are then `g2c` vs `gfortran` and `libquadmath`

**Comment by padsley** [comment]
From what I'm able to tell, g2c is a library for g77. So this code was compiled with g77 and not gfortran.

(See [here](https://stackoverflow.com/questions/2406581/what-is-libg2c-library)

**Comment by padsley** [comment]
FIXED IT.

**Comment by padsley** [comment]
Right, compilation with g77 is possible.

Full instructions will be put into the README for this repository so refer there for guidance.
